from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol


class PlatformStore(Protocol):
    def initialize(self, seed_demo_data: bool = True) -> None: ...

    def healthcheck(self) -> bool: ...

    def authenticate(self, login_name: str, password: str) -> dict[str, Any] | None: ...

    def get_user(self, user_id: str) -> dict[str, Any] | None: ...

    def create_auth_session(self, user_id: str, expires_at: datetime) -> str: ...

    def is_auth_session_active(self, session_id: str, user_id: str) -> bool: ...

    def revoke_auth_session(self, session_id: str, user_id: str) -> bool: ...

    def current_user(self, user_id: str | None = None) -> dict[str, Any]: ...

    def list_users(self) -> list[dict[str, Any]]: ...

    def list_tasks(self, owner_user_id: str | None = None) -> list[dict[str, Any]]: ...

    def get_task(self, task_id: str) -> dict[str, Any] | None: ...

    def create_task(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def update_task_basic_info(self, task_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def add_task_files(self, task_id: str, files: list[dict[str, Any]]) -> list[dict[str, Any]] | None: ...

    def update_task_file(self, task_id: str, file_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def replace_task_file(self, task_id: str, file_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def delete_task_file(self, task_id: str, file_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def retry_task_file_parse(self, task_id: str, file_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def create_round(self, task_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def get_round(self, round_id: str) -> dict[str, Any] | None: ...

    def start_audit(self, round_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def local_rerun(self, round_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def get_audit_progress(self, round_id: str) -> dict[str, Any] | None: ...

    def check_round_publishability(self, round_id: str) -> dict[str, Any] | None: ...

    def decide_dynamic_item(
        self, round_id: str, item_id: str, decision: str, payload: dict[str, Any]
    ) -> dict[str, Any] | None: ...

    def list_audit_runs(self, round_id: str) -> list[dict[str, Any]] | None: ...

    def list_rule_executions(self, round_id: str) -> list[dict[str, Any]] | None: ...

    def get_rule_execution(self, execution_id: str) -> dict[str, Any] | None: ...

    def list_execution_attempts(self, execution_id: str) -> list[dict[str, Any]] | None: ...

    def record_execution_attempt(self, execution_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def retry_rule_execution(self, execution_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def list_issues(self, round_id: str | None = None) -> list[dict[str, Any]]: ...

    def list_reports(self) -> list[dict[str, Any]]: ...

    def get_report(self, report_id: str) -> dict[str, Any] | None: ...

    def create_report(self, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def publish_report(self, report_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def get_issue(self, issue_id: str) -> dict[str, Any] | None: ...

    def update_issue(self, issue_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def set_issue_status(
        self, issue_id: str, status: str, reason: str | None = None, context: dict[str, Any] | None = None
    ) -> dict[str, Any] | None: ...

    def list_operation_logs(self) -> list[dict[str, Any]]: ...

    def list_standards(self) -> list[dict[str, Any]]: ...

    def get_standard(self, standard_id: str) -> dict[str, Any] | None: ...

    def create_standard(self, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def list_standard_versions(self, standard_id: str) -> list[dict[str, Any]]: ...

    def get_standard_version(self, version_id: str) -> dict[str, Any] | None: ...

    def create_standard_version(self, standard_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def list_standard_parse_revisions(self, version_id: str) -> list[dict[str, Any]] | None: ...

    def create_standard_parse_revision(self, version_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def publish_standard_parse_revision(self, revision_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def publish_standard_version(self, version_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def abolish_standard_version(self, version_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def compare_standard_versions(self, version_id: str, other_version_id: str) -> dict[str, Any] | None: ...

    def list_standard_clauses(self, version_id: str) -> list[dict[str, Any]] | None: ...

    def list_round_standards(self, round_id: str) -> list[dict[str, Any]] | None: ...

    def add_standard_to_round(self, round_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def confirm_round_standard(self, round_id: str, round_standard_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def list_executors(self) -> list[dict[str, Any]]: ...

    def list_executor_versions(self, executor_code: str) -> list[dict[str, Any]] | None: ...

    def list_rules(self) -> list[dict[str, Any]]: ...

    def get_rule(self, rule_id: str) -> dict[str, Any] | None: ...

    def create_rule(self, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def list_rule_versions(self, rule_id: str) -> list[dict[str, Any]] | None: ...

    def get_rule_version(self, version_id: str) -> dict[str, Any] | None: ...

    def create_rule_version(self, rule_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def publish_rule_version(self, version_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def disable_rule_version(self, version_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def copy_rule_version(self, version_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def create_rule_test_run(self, version_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def list_queue_jobs(self) -> list[dict[str, Any]]: ...

    def get_queue_job(self, job_id: str) -> dict[str, Any] | None: ...

    def update_queue_job(self, job_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def retry_queue_job(self, job_id: str, payload: dict[str, Any] | None = None) -> dict[str, Any] | None: ...

    def complete_audit_run(self, run_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def validate_rule_version(self, version_id: str) -> dict[str, Any] | None: ...

    def list_rule_packs(self) -> list[dict[str, Any]]: ...

    def create_rule_pack(self, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def update_rule_pack(self, pack_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def list_round_rules(self, round_id: str) -> list[dict[str, Any]] | None: ...

    def assemble_round_rules(self, round_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def list_dynamic_items(self, round_id: str) -> list[dict[str, Any]] | None: ...

    def list_coverage(self, round_id: str) -> dict[str, Any] | None: ...
