from __future__ import annotations

from datetime import datetime
from typing import Any, Protocol


class PlatformStore(Protocol):
    def initialize(self, seed_demo_data: bool = True) -> None: ...

    def healthcheck(self) -> bool: ...

    def authenticate(self, login_name: str, password: str) -> dict[str, Any] | None: ...

    def get_user(self, user_id: str) -> dict[str, Any] | None: ...

    def create_auth_session(self, user_id: str, expires_at: datetime) -> str: ...

    def is_auth_session_active(self, session_id: str, user_id: str) -> bool: ...

    def revoke_auth_session(self, session_id: str, user_id: str) -> bool: ...

    def current_user(self, user_id: str | None = None) -> dict[str, Any]: ...

    def list_users(self) -> list[dict[str, Any]]: ...

    def list_tasks(self, owner_user_id: str | None = None) -> list[dict[str, Any]]: ...

    def get_task(self, task_id: str) -> dict[str, Any] | None: ...

    def create_task(self, payload: dict[str, Any]) -> dict[str, Any]: ...

    def update_task_basic_info(self, task_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def add_task_files(self, task_id: str, files: list[dict[str, Any]]) -> list[dict[str, Any]] | None: ...

    def create_round(self, task_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def get_round(self, round_id: str) -> dict[str, Any] | None: ...

    def start_audit(self, round_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def list_operation_logs(self) -> list[dict[str, Any]]: ...

    def list_standards(self) -> list[dict[str, Any]]: ...

    def get_standard(self, standard_id: str) -> dict[str, Any] | None: ...

    def create_standard(self, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def list_standard_versions(self, standard_id: str) -> list[dict[str, Any]]: ...

    def get_standard_version(self, version_id: str) -> dict[str, Any] | None: ...

    def create_standard_version(self, standard_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def publish_standard_version(self, version_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def list_standard_clauses(self, version_id: str) -> list[dict[str, Any]] | None: ...

    def list_round_standards(self, round_id: str) -> list[dict[str, Any]] | None: ...

    def add_standard_to_round(self, round_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...

    def confirm_round_standard(self, round_id: str, round_standard_id: str, payload: dict[str, Any]) -> dict[str, Any] | None: ...
