"""initial_schema

Revision ID: 20d253b7e1b5
Revises:
Create Date: 2026-07-25 08:11:45.058984
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '20d253b7e1b5'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _create_current_round_fk() -> None:
    if op.get_bind().dialect.name == "sqlite":
        with op.batch_alter_table("audit_task", recreate="always") as batch_op:
            batch_op.create_foreign_key(
                "fk_audit_task_current_round",
                "audit_round",
                ["current_round_id"],
                ["id"],
            )
        return
    op.create_foreign_key(
        "fk_audit_task_current_round",
        "audit_task",
        "audit_round",
        ["current_round_id"],
        ["id"],
    )


def _drop_current_round_fk() -> None:
    if op.get_bind().dialect.name == "sqlite":
        with op.batch_alter_table("audit_task", recreate="always") as batch_op:
            batch_op.drop_constraint("fk_audit_task_current_round", type_="foreignkey")
        return
    op.drop_constraint("fk_audit_task_current_round", "audit_task", type_="foreignkey")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('executor_definition',
    sa.Column('executor_code', sa.String(length=64), nullable=False),
    sa.Column('executor_name', sa.String(length=128), nullable=False),
    sa.Column('executor_kind', sa.String(length=16), nullable=False),
    sa.Column('input_type', sa.String(length=64), nullable=False),
    sa.Column('output_type', sa.String(length=64), nullable=False),
    sa.Column('runtime_mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('executor_code')
    )
    op.create_index(op.f('ix_executor_definition_status'), 'executor_definition', ['status'], unique=False)
    op.create_table('field_definition',
    sa.Column('field_code', sa.String(length=64), nullable=False),
    sa.Column('field_name', sa.String(length=128), nullable=False),
    sa.Column('data_type', sa.String(length=32), nullable=False),
    sa.Column('unit_dimension', sa.String(length=64), nullable=True),
    sa.Column('multi_valued', sa.Boolean(), nullable=False),
    sa.Column('normalization_rule', sa.String(length=128), nullable=True),
    sa.Column('validation_rule', sa.JSON(), nullable=True),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_code')
    )
    op.create_index(op.f('ix_field_definition_status'), 'field_definition', ['status'], unique=False)
    op.create_table('model_provider',
    sa.Column('provider_code', sa.String(length=64), nullable=False),
    sa.Column('provider_name', sa.String(length=128), nullable=False),
    sa.Column('base_url', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_code')
    )
    op.create_index(op.f('ix_model_provider_status'), 'model_provider', ['status'], unique=False)
    op.create_table('prompt_template',
    sa.Column('template_code', sa.String(length=64), nullable=False),
    sa.Column('template_name', sa.String(length=128), nullable=False),
    sa.Column('template_body', sa.Text(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_code')
    )
    op.create_index(op.f('ix_prompt_template_status'), 'prompt_template', ['status'], unique=False)
    op.create_table('queue_job',
    sa.Column('job_code', sa.String(length=64), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=False),
    sa.Column('queue_name', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_code')
    )
    op.create_index(op.f('ix_queue_job_status'), 'queue_job', ['status'], unique=False)
    op.create_table('rule_pack',
    sa.Column('pack_code', sa.String(length=64), nullable=False),
    sa.Column('pack_name', sa.String(length=128), nullable=False),
    sa.Column('stage_code', sa.String(length=32), nullable=False),
    sa.Column('trigger_condition', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pack_code')
    )
    op.create_index(op.f('ix_rule_pack_status'), 'rule_pack', ['status'], unique=False)
    op.create_table('standard',
    sa.Column('standard_code', sa.String(length=64), nullable=False),
    sa.Column('standard_name', sa.String(length=256), nullable=False),
    sa.Column('standard_type', sa.String(length=32), nullable=False),
    sa.Column('scope_text', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('alias_texts', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('standard_code')
    )
    op.create_index(op.f('ix_standard_status'), 'standard', ['status'], unique=False)
    op.create_table('sys_user',
    sa.Column('login_name', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login_name')
    )
    op.create_index(op.f('ix_sys_user_status'), 'sys_user', ['status'], unique=False)
    op.create_table('system_alert',
    sa.Column('alert_code', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('source_type', sa.String(length=64), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alert_code')
    )
    op.create_index(op.f('ix_system_alert_status'), 'system_alert', ['status'], unique=False)
    op.create_table('system_parameter',
    sa.Column('param_key', sa.String(length=128), nullable=False),
    sa.Column('param_value', sa.JSON(), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('param_key')
    )
    op.create_index(op.f('ix_system_parameter_status'), 'system_parameter', ['status'], unique=False)
    op.create_table('unit_definition',
    sa.Column('unit_code', sa.String(length=32), nullable=False),
    sa.Column('unit_name', sa.String(length=64), nullable=False),
    sa.Column('dimension_code', sa.String(length=64), nullable=False),
    sa.Column('standard_unit', sa.String(length=32), nullable=False),
    sa.Column('precision_scale', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_code')
    )
    op.create_index(op.f('ix_unit_definition_status'), 'unit_definition', ['status'], unique=False)
    op.create_table('audit_task',
    sa.Column('task_no', sa.String(length=32), nullable=False),
    sa.Column('customer_name', sa.String(length=256), nullable=False),
    sa.Column('product_name', sa.String(length=256), nullable=False),
    sa.Column('product_model', sa.String(length=128), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_round_no', sa.Integer(), nullable=False),
    sa.Column('final_conclusion', sa.String(length=32), nullable=True),
    sa.Column('current_round_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_no', name='uq_audit_task_task_no')
    )
    op.create_index(op.f('ix_audit_task_status'), 'audit_task', ['status'], unique=False)
    op.create_table('executor_version',
    sa.Column('executor_definition_id', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.String(length=32), nullable=False),
    sa.Column('parameter_schema', sa.JSON(), nullable=False),
    sa.Column('result_schema', sa.JSON(), nullable=False),
    sa.Column('default_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('supports_batch', sa.Boolean(), nullable=False),
    sa.Column('entrypoint', sa.String(length=256), nullable=True),
    sa.Column('image_version', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['executor_definition_id'], ['executor_definition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('executor_definition_id', 'version_no', name='uq_executor_version')
    )
    op.create_index(op.f('ix_executor_version_status'), 'executor_version', ['status'], unique=False)
    op.create_table('model_config',
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('model_code', sa.String(length=128), nullable=False),
    sa.Column('model_kind', sa.String(length=32), nullable=False),
    sa.Column('api_key_ciphertext', sa.Text(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('concurrency_limit', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['model_provider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_config_status'), 'model_config', ['status'], unique=False)
    op.create_table('operation_log',
    sa.Column('operator_user_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('action_code', sa.String(length=64), nullable=False),
    sa.Column('before_snapshot', sa.JSON(), nullable=True),
    sa.Column('after_snapshot', sa.JSON(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['operator_user_id'], ['sys_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_definition',
    sa.Column('rule_code', sa.String(length=64), nullable=False),
    sa.Column('rule_name', sa.String(length=128), nullable=False),
    sa.Column('rule_type', sa.String(length=32), nullable=False),
    sa.Column('executor_definition_id', sa.Uuid(), nullable=False),
    sa.Column('default_issue_category', sa.String(length=64), nullable=False),
    sa.Column('default_severity', sa.String(length=16), nullable=False),
    sa.Column('affects_suggested_conclusion', sa.Boolean(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['executor_definition_id'], ['executor_definition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_code')
    )
    op.create_table('unit_alias',
    sa.Column('unit_definition_id', sa.Uuid(), nullable=False),
    sa.Column('alias_text', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['unit_definition_id'], ['unit_definition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_text')
    )
    op.create_table('audit_round',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('round_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('suggested_conclusion', sa.String(length=32), nullable=True),
    sa.Column('manual_conclusion', sa.String(length=32), nullable=True),
    sa.Column('round_note', sa.Text(), nullable=True),
    sa.Column('basic_info_snapshot', sa.JSON(), nullable=False),
    sa.Column('standard_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('rule_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('executor_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('model_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('prompt_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['audit_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'round_no', name='uq_audit_round_task_round')
    )
    op.create_index(op.f('ix_audit_round_status'), 'audit_round', ['status'], unique=False)
    _create_current_round_fk()
    op.create_table('rule_version',
    sa.Column('rule_definition_id', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.String(length=32), nullable=False),
    sa.Column('executor_version_id', sa.Uuid(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('scope_files', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('stage_code', sa.String(length=32), nullable=False),
    sa.Column('dependency_rule_codes', sa.JSON(), nullable=True),
    sa.Column('task_override_allowed', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['executor_version_id'], ['executor_version.id'], ),
    sa.ForeignKeyConstraint(['rule_definition_id'], ['rule_definition.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_definition_id', 'version_no', name='uq_rule_version')
    )
    op.create_index(op.f('ix_rule_version_status'), 'rule_version', ['status'], unique=False)
    op.create_table('audit_issue',
    sa.Column('round_id', sa.Uuid(), nullable=False),
    sa.Column('issue_code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category_code', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('system_conclusion', sa.Text(), nullable=True),
    sa.Column('manual_conclusion', sa.Text(), nullable=True),
    sa.Column('affects_conclusion', sa.Boolean(), nullable=False),
    sa.Column('manual_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['audit_round.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_issue_status'), 'audit_issue', ['status'], unique=False)
    op.create_table('audit_run',
    sa.Column('round_id', sa.Uuid(), nullable=False),
    sa.Column('run_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('prompt_snapshot_id', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['audit_round.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_run_status'), 'audit_run', ['status'], unique=False)
    op.create_table('report',
    sa.Column('round_id', sa.Uuid(), nullable=False),
    sa.Column('report_no', sa.String(length=32), nullable=False),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('conclusion', sa.String(length=32), nullable=False),
    sa.Column('word_object_key', sa.String(length=256), nullable=True),
    sa.Column('pdf_object_key', sa.String(length=256), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['audit_round.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_no')
    )
    op.create_index(op.f('ix_report_status'), 'report', ['status'], unique=False)
    op.create_table('round_rule',
    sa.Column('round_id', sa.Uuid(), nullable=False),
    sa.Column('rule_version_id', sa.Uuid(), nullable=False),
    sa.Column('executor_version_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('override_payload', sa.JSON(), nullable=True),
    sa.Column('disable_reason', sa.Text(), nullable=True),
    sa.Column('snapshot_no', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['executor_version_id'], ['executor_version.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['audit_round.id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_impact_analysis',
    sa.Column('round_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('trigger_payload', sa.JSON(), nullable=False),
    sa.Column('affected_rule_codes', sa.JSON(), nullable=False),
    sa.Column('affected_issue_ids', sa.JSON(), nullable=True),
    sa.Column('estimated_rerun_scope', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['audit_round.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_impact_analysis_status'), 'rule_impact_analysis', ['status'], unique=False)
    op.create_table('rule_pack_item',
    sa.Column('rule_pack_id', sa.Uuid(), nullable=False),
    sa.Column('rule_version_id', sa.Uuid(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['rule_pack_id'], ['rule_pack.id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_file',
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('round_id', sa.Uuid(), nullable=True),
    sa.Column('storage_key', sa.String(length=256), nullable=False),
    sa.Column('original_name', sa.String(length=256), nullable=False),
    sa.Column('file_type', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('parse_summary', sa.JSON(), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('is_applicable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['audit_round.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['audit_task.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key'),
    sa.UniqueConstraint('task_id', 'sha256', name='uq_task_file_task_sha256')
    )
    op.create_index(op.f('ix_task_file_status'), 'task_file', ['status'], unique=False)
    op.create_table('extracted_field',
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('field_definition_id', sa.Uuid(), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('manual_value', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['field_definition_id'], ['field_definition.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['task_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_field_status'), 'extracted_field', ['status'], unique=False)
    op.create_table('parsed_block',
    sa.Column('file_id', sa.Uuid(), nullable=False),
    sa.Column('page_no', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=32), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('source_ref', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['task_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standard_version',
    sa.Column('standard_id', sa.Uuid(), nullable=False),
    sa.Column('full_code', sa.String(length=64), nullable=False),
    sa.Column('version_label', sa.String(length=64), nullable=False),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('implement_date', sa.Date(), nullable=True),
    sa.Column('abolish_date', sa.Date(), nullable=True),
    sa.Column('publisher', sa.String(length=128), nullable=True),
    sa.Column('mandatory_flag', sa.Boolean(), nullable=False),
    sa.Column('original_file_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('superseded_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['original_file_id'], ['task_file.id'], ),
    sa.ForeignKeyConstraint(['standard_id'], ['standard.id'], ),
    sa.ForeignKeyConstraint(['superseded_by_id'], ['standard_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_code')
    )
    op.create_index(op.f('ix_standard_version_status'), 'standard_version', ['status'], unique=False)
    op.create_table('semantic_fact',
    sa.Column('round_id', sa.Uuid(), nullable=False),
    sa.Column('fact_code', sa.String(length=64), nullable=False),
    sa.Column('fact_name', sa.String(length=128), nullable=False),
    sa.Column('raw_value', sa.Text(), nullable=True),
    sa.Column('normalized_value', sa.JSON(), nullable=True),
    sa.Column('unit_code', sa.String(length=32), nullable=True),
    sa.Column('source_file_id', sa.Uuid(), nullable=True),
    sa.Column('source_block_id', sa.Uuid(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['round_id'], ['audit_round.id'], ),
    sa.ForeignKeyConstraint(['source_block_id'], ['parsed_block.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['task_file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standard_parse_revision',
    sa.Column('standard_version_id', sa.Uuid(), nullable=False),
    sa.Column('revision_no', sa.String(length=32), nullable=False),
    sa.Column('revision_payload', sa.JSON(), nullable=False),
    sa.Column('impact_flag', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['standard_version_id'], ['standard_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('standard_version_id', 'revision_no', name='uq_standard_revision')
    )
    op.create_index(op.f('ix_standard_parse_revision_status'), 'standard_parse_revision', ['status'], unique=False)
    op.create_table('standard_relation',
    sa.Column('source_standard_version_id', sa.Uuid(), nullable=False),
    sa.Column('target_standard_version_id', sa.Uuid(), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.Column('relation_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_standard_version_id'], ['standard_version.id'], ),
    sa.ForeignKeyConstraint(['target_standard_version_id'], ['standard_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('round_standard',
    sa.Column('round_id', sa.Uuid(), nullable=False),
    sa.Column('standard_version_id', sa.Uuid(), nullable=False),
    sa.Column('parse_revision_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('selected_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('skip_reason', sa.Text(), nullable=True),
    sa.Column('snapshot_no', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parse_revision_id'], ['standard_parse_revision.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['audit_round.id'], ),
    sa.ForeignKeyConstraint(['selected_by_user_id'], ['sys_user.id'], ),
    sa.ForeignKeyConstraint(['standard_version_id'], ['standard_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standard_clause',
    sa.Column('parse_revision_id', sa.Uuid(), nullable=False),
    sa.Column('clause_code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('parent_clause_id', sa.Uuid(), nullable=True),
    sa.Column('clause_level', sa.Integer(), nullable=False),
    sa.Column('clause_type', sa.String(length=32), nullable=False),
    sa.Column('constraint_level', sa.String(length=16), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('parameter_schema', sa.JSON(), nullable=True),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('proof_status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_clause_id'], ['standard_clause.id'], ),
    sa.ForeignKeyConstraint(['parse_revision_id'], ['standard_parse_revision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dynamic_audit_item',
    sa.Column('round_id', sa.Uuid(), nullable=False),
    sa.Column('parent_clause_id', sa.Uuid(), nullable=True),
    sa.Column('source_clause_id', sa.Uuid(), nullable=True),
    sa.Column('subject_code', sa.String(length=64), nullable=False),
    sa.Column('subject_name', sa.String(length=128), nullable=False),
    sa.Column('applicability_status', sa.String(length=32), nullable=False),
    sa.Column('execution_mode', sa.String(length=32), nullable=False),
    sa.Column('input_profile', sa.JSON(), nullable=False),
    sa.Column('customer_evidence', sa.JSON(), nullable=True),
    sa.Column('standard_evidence', sa.JSON(), nullable=True),
    sa.Column('manual_state', sa.String(length=32), nullable=True),
    sa.Column('merged_issue_key', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_clause_id'], ['standard_clause.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['audit_round.id'], ),
    sa.ForeignKeyConstraint(['source_clause_id'], ['standard_clause.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('issue_evidence',
    sa.Column('issue_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('clause_id', sa.Uuid(), nullable=True),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('excerpt_text', sa.Text(), nullable=True),
    sa.Column('artifact_uri', sa.String(length=256), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clause_id'], ['standard_clause.id'], ),
    sa.ForeignKeyConstraint(['file_id'], ['task_file.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['audit_issue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('round_standard_coverage',
    sa.Column('round_id', sa.Uuid(), nullable=False),
    sa.Column('standard_clause_id', sa.Uuid(), nullable=False),
    sa.Column('dynamic_item_id', sa.Uuid(), nullable=True),
    sa.Column('coverage_status', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('publish_check_status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dynamic_item_id'], ['dynamic_audit_item.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['audit_round.id'], ),
    sa.ForeignKeyConstraint(['standard_clause_id'], ['standard_clause.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_execution',
    sa.Column('audit_run_id', sa.Uuid(), nullable=False),
    sa.Column('round_id', sa.Uuid(), nullable=False),
    sa.Column('rule_version_id', sa.Uuid(), nullable=False),
    sa.Column('dynamic_item_id', sa.Uuid(), nullable=True),
    sa.Column('executor_version_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('normalized_input_hash', sa.String(length=64), nullable=False),
    sa.Column('result_payload', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('is_expired', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_run_id'], ['audit_run.id'], ),
    sa.ForeignKeyConstraint(['dynamic_item_id'], ['dynamic_audit_item.id'], ),
    sa.ForeignKeyConstraint(['executor_version_id'], ['executor_version.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['audit_round.id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['rule_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audit_run_id', 'rule_version_id', 'normalized_input_hash', name='uq_rule_execution_key')
    )
    op.create_index(op.f('ix_rule_execution_status'), 'rule_execution', ['status'], unique=False)
    op.create_table('issue_source',
    sa.Column('issue_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('rule_execution_id', sa.Uuid(), nullable=True),
    sa.Column('dynamic_item_id', sa.Uuid(), nullable=True),
    sa.Column('source_status', sa.String(length=32), nullable=False),
    sa.Column('source_payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dynamic_item_id'], ['dynamic_audit_item.id'], ),
    sa.ForeignKeyConstraint(['issue_id'], ['audit_issue.id'], ),
    sa.ForeignKeyConstraint(['rule_execution_id'], ['rule_execution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_execution_attempt',
    sa.Column('rule_execution_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('attempt_kind', sa.String(length=32), nullable=False),
    sa.Column('executor_version_id', sa.Uuid(), nullable=False),
    sa.Column('model_version_id', sa.Uuid(), nullable=True),
    sa.Column('input_payload', sa.JSON(), nullable=False),
    sa.Column('output_payload', sa.JSON(), nullable=True),
    sa.Column('error_payload', sa.JSON(), nullable=True),
    sa.Column('token_usage', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['executor_version_id'], ['executor_version.id'], ),
    sa.ForeignKeyConstraint(['rule_execution_id'], ['rule_execution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_execution_attempt_status'), 'rule_execution_attempt', ['status'], unique=False)
    op.create_table('execution_step',
    sa.Column('rule_execution_attempt_id', sa.Uuid(), nullable=False),
    sa.Column('step_code', sa.String(length=64), nullable=False),
    sa.Column('step_kind', sa.String(length=32), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('output_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reused_from_step_id', sa.Uuid(), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('error_payload', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reused_from_step_id'], ['execution_step.id'], ),
    sa.ForeignKeyConstraint(['rule_execution_attempt_id'], ['rule_execution_attempt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_step_status'), 'execution_step', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_step_status'), table_name='execution_step')
    op.drop_table('execution_step')
    op.drop_index(op.f('ix_rule_execution_attempt_status'), table_name='rule_execution_attempt')
    op.drop_table('rule_execution_attempt')
    op.drop_table('issue_source')
    op.drop_index(op.f('ix_rule_execution_status'), table_name='rule_execution')
    op.drop_table('rule_execution')
    op.drop_table('round_standard_coverage')
    op.drop_table('issue_evidence')
    op.drop_table('dynamic_audit_item')
    op.drop_table('standard_clause')
    op.drop_table('round_standard')
    op.drop_table('standard_relation')
    op.drop_index(op.f('ix_standard_parse_revision_status'), table_name='standard_parse_revision')
    op.drop_table('standard_parse_revision')
    op.drop_table('semantic_fact')
    op.drop_index(op.f('ix_standard_version_status'), table_name='standard_version')
    op.drop_table('standard_version')
    op.drop_table('parsed_block')
    op.drop_index(op.f('ix_extracted_field_status'), table_name='extracted_field')
    op.drop_table('extracted_field')
    op.drop_index(op.f('ix_task_file_status'), table_name='task_file')
    op.drop_table('task_file')
    op.drop_table('rule_pack_item')
    op.drop_index(op.f('ix_rule_impact_analysis_status'), table_name='rule_impact_analysis')
    op.drop_table('rule_impact_analysis')
    op.drop_table('round_rule')
    op.drop_index(op.f('ix_report_status'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_audit_run_status'), table_name='audit_run')
    op.drop_table('audit_run')
    op.drop_index(op.f('ix_audit_issue_status'), table_name='audit_issue')
    op.drop_table('audit_issue')
    op.drop_index(op.f('ix_rule_version_status'), table_name='rule_version')
    op.drop_table('rule_version')
    _drop_current_round_fk()
    op.drop_index(op.f('ix_audit_round_status'), table_name='audit_round')
    op.drop_table('audit_round')
    op.drop_table('unit_alias')
    op.drop_table('rule_definition')
    op.drop_table('operation_log')
    op.drop_index(op.f('ix_model_config_status'), table_name='model_config')
    op.drop_table('model_config')
    op.drop_index(op.f('ix_executor_version_status'), table_name='executor_version')
    op.drop_table('executor_version')
    op.drop_index(op.f('ix_audit_task_status'), table_name='audit_task')
    op.drop_table('audit_task')
    op.drop_index(op.f('ix_unit_definition_status'), table_name='unit_definition')
    op.drop_table('unit_definition')
    op.drop_index(op.f('ix_system_parameter_status'), table_name='system_parameter')
    op.drop_table('system_parameter')
    op.drop_index(op.f('ix_system_alert_status'), table_name='system_alert')
    op.drop_table('system_alert')
    op.drop_index(op.f('ix_sys_user_status'), table_name='sys_user')
    op.drop_table('sys_user')
    op.drop_index(op.f('ix_standard_status'), table_name='standard')
    op.drop_table('standard')
    op.drop_index(op.f('ix_rule_pack_status'), table_name='rule_pack')
    op.drop_table('rule_pack')
    op.drop_index(op.f('ix_queue_job_status'), table_name='queue_job')
    op.drop_table('queue_job')
    op.drop_index(op.f('ix_prompt_template_status'), table_name='prompt_template')
    op.drop_table('prompt_template')
    op.drop_index(op.f('ix_model_provider_status'), table_name='model_provider')
    op.drop_table('model_provider')
    op.drop_index(op.f('ix_field_definition_status'), table_name='field_definition')
    op.drop_table('field_definition')
    op.drop_index(op.f('ix_executor_definition_status'), table_name='executor_definition')
    op.drop_table('executor_definition')
    # ### end Alembic commands ###
