import { FormEvent, useEffect, useState } from 'react'
import { ArrowLeft, BookCheck, Check, CircleX, Download, FileSearch, Play, Plus, RefreshCw, RotateCcw, ShieldCheck, Upload } from 'lucide-react'
import { Link, useParams, useSearchParams } from 'react-router-dom'
import { api, json } from '../api'
import { useAuth } from '../auth'
import { useBusy, useRemote } from '../hooks'
import { Empty, ErrorState, Modal, PageHeader, Spinner, Status } from '../ui'

const tabs = ['overview', 'files', 'standards', 'audit', 'issues', 'reports'] as const
const tabLabels = { overview: '概览', files: '技术资料', standards: '标准覆盖', audit: '智能审核', issues: '问题复核', reports: '报告' }

export function TaskWorkspace() {
  const { taskId = '' } = useParams(); const [params, setParams] = useSearchParams(); const active = (tabs.includes(params.get('tab') as any) ? params.get('tab') : 'overview') as typeof tabs[number]
  const task = useRemote(() => api<any>(`/tasks/${taskId}`), [taskId])
  if (task.loading) return <Spinner label="正在加载任务工作台" />
  if (task.error || !task.data) return <ErrorState error={task.error} retry={task.refresh} />
  const roundId = task.data.current_round_id
  return <div className="page wide"><div className="breadcrumb"><Link to="/tasks"><ArrowLeft />审核任务</Link><span>/</span><span className="mono">{task.data.task_no}</span></div><PageHeader eyebrow={`第 ${task.data.current_round_no} 轮`} title={`${task.data.product_name} · ${task.data.product_model}`} description={`${task.data.customer_name} · 一个任务仅对应当前产品型号`} actions={<><Status value={task.data.status} /><button className="btn secondary" onClick={() => void task.refresh()}><RefreshCw />刷新</button></>} /><nav className="tabs workspace-tabs">{tabs.map(tab => <button key={tab} className={active === tab ? 'active' : ''} onClick={() => setParams({ tab })}>{tabLabels[tab]}</button>)}</nav>
    {active === 'overview' && <Overview task={task.data} />}
    {active === 'files' && <Files task={task.data} refresh={task.refresh} />}
    {active === 'standards' && <Standards roundId={roundId} />}
    {active === 'audit' && <Audit roundId={roundId} />}
    {active === 'issues' && <Issues roundId={roundId} />}
    {active === 'reports' && <Reports roundId={roundId} />}
  </div>
}

function Overview({ task }: { task: any }) {
  const current = task.rounds?.find((item: any) => item.id === task.current_round_id) || task.rounds?.at(-1)
  return <div className="workspace-grid"><section className="section"><header className="section-head"><div><h2>任务主档</h2><p>基础信息在新轮次中形成快照</p></div></header><div className="detail-grid"><Fact label="任务编号" value={task.task_no} mono /><Fact label="客户企业" value={task.customer_name} /><Fact label="产品名称" value={task.product_name} /><Fact label="产品型号" value={task.product_model} mono /><Fact label="当前轮次" value={`第 ${task.current_round_no} 轮`} /><Fact label="最终结论" value={task.final_conclusion || '尚未确认'} /></div></section><aside className="section"><header className="section-head"><div><h2>当前轮次</h2><p>{current?.round_note || '暂无轮次说明'}</p></div></header><div className="summary-list"><div><span>状态</span><Status value={current?.status || task.status} /></div><div><span>资料文件</span><strong>{task.files?.filter((x: any) => x.status !== 'deleted').length || 0}</strong></div><div><span>适用标准</span><strong>{current?.standards?.length || 0}</strong></div><div><span>问题数量</span><strong>{task.issues?.length || 0}</strong></div></div></aside></div>
}

function Files({ task, refresh }: { task: any; refresh: () => Promise<void> }) {
  const busy = useBusy(); const [selected, setSelected] = useState<any>(null); const [blocks, setBlocks] = useState<any[]>([])
  const upload = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const input = event.currentTarget.elements.namedItem('files') as HTMLInputElement; if (!input.files?.length) return; const body = new FormData(); Array.from(input.files).forEach(file => body.append('files', file)); await busy.run(() => api(`/tasks/${task.id}/files`, { method: 'POST', body })); input.value = ''; await refresh() }
  const open = async (file: any) => { setSelected(file); setBlocks(await api(`/tasks/${task.id}/files/${file.id}/blocks`)) }
  const review = async (decision: 'accepted' | 'reparse') => { await busy.run(() => api(`/tasks/${task.id}/files/${selected.id}/parse-review`, json('POST', { decision, reason: decision === 'accepted' ? '人工确认解析结果可用于审核' : '解析结果需要重新处理' }))); setSelected(null); await refresh() }
  return <><section className="section"><header className="section-head"><div><h2>技术资料</h2><p>解析结果必须达到质量门槛或经人工接受后才能进入模型上下文</p></div><form className="upload-inline" onSubmit={upload}><input name="files" type="file" multiple required /><button className="btn primary" disabled={busy.busy}><Upload />上传资料</button></form></header>{busy.error && <div className="form-error">{busy.error}</div>}{!task.files?.length ? <Empty title="暂无技术资料" /> : <div className="table-wrap"><table><thead><tr><th>文件</th><th>版本</th><th>解析状态</th><th>质量分</th><th>人工复核</th><th>重试</th><th></th></tr></thead><tbody>{task.files.filter((x: any) => x.status !== 'deleted').map((file: any) => <tr key={file.id}><td><strong>{file.file_name || file.original_name}</strong><small>{file.file_type}</small></td><td>V{file.version_no}</td><td><Status value={file.status} /></td><td>{file.parse_summary?.quality_metrics?.quality_score ?? '-'}</td><td><Status value={file.parse_summary?.quality_review?.status} /></td><td>{file.parse_summary?.retry_count || 0}</td><td><button className="icon-link" title="查看证据块" disabled={file.status !== 'parsed'} onClick={() => void open(file)}><FileSearch /></button></td></tr>)}</tbody></table></div>}</section>{selected && <Modal title={selected.file_name || selected.original_name} close={() => setSelected(null)}><div className="quality-strip"><Fact label="质量分" value={selected.parse_summary?.quality_metrics?.quality_score ?? '-'} /><Fact label="平均置信度" value={selected.parse_summary?.quality_metrics?.mean_confidence ?? '-'} /><Fact label="页面覆盖率" value={selected.parse_summary?.quality_metrics?.page_coverage_ratio ?? '-'} /><Fact label="低置信块" value={selected.parse_summary?.quality_metrics?.low_confidence_block_count ?? 0} /></div><div className="block-list">{blocks.map(block => <article key={block.id}><header><span className="mono">{block.source_ref}</span><span>置信度 {block.confidence}</span></header><p>{block.content_text}</p></article>)}</div><footer className="form-actions"><button className="btn danger" onClick={() => void review('reparse')}><RotateCcw />要求重解析</button><button className="btn primary" onClick={() => void review('accepted')}><Check />接受解析结果</button></footer></Modal>}</>
}

function Standards({ roundId }: { roundId: string }) {
  const remote = useRemote(async () => { const [selected, dynamic, coverage, catalog] = await Promise.all([api<any[]>(`/rounds/${roundId}/standards`), api<any[]>(`/rounds/${roundId}/dynamic-items`), api<any>(`/rounds/${roundId}/coverage`), api<any[]>('/standards')]); return { selected, dynamic, coverage, catalog } }, [roundId]); const busy = useBusy(); const [modal, setModal] = useState(false)
  if (remote.loading) return <Spinner label="正在加载标准覆盖" />; if (remote.error || !remote.data) return <ErrorState error={remote.error} retry={remote.refresh} />
  const add = async (versionId: string) => { const item = await busy.run(() => api<any>(`/rounds/${roundId}/standards`, json('POST', { standard_version_id: versionId, source_type: 'manual_selection' }))); await api(`/rounds/${roundId}/standards/${item.id}/confirm`, json('POST')); setModal(false); await remote.refresh() }
  const decide = async (id: string, action: 'confirm' | 'exclude' | 'manual') => { await busy.run(() => api(`/rounds/${roundId}/dynamic-items/${id}/${action}`, json('POST', { reason: action === 'confirm' ? '人工确认条款适用' : action === 'exclude' ? '人工确认条款不适用' : '转人工专项判断' }))); await remote.refresh() }
  return <><div className="workspace-grid"><section className="section"><header className="section-head"><div><h2>已确认标准</h2><p>本轮只引用固定版本和解析修订快照</p></div><button className="btn primary" onClick={() => setModal(true)}><Plus />添加标准</button></header>{!remote.data.selected.length ? <Empty title="尚未确认适用标准" /> : <div className="list-lines">{remote.data.selected.map(item => <div key={item.id}><BookCheck /><div><strong>{item.standard_name}</strong><span className="mono">{item.standard_code}</span></div><Status value={item.status} /></div>)}</div>}</section><aside className="section"><header className="section-head"><div><h2>覆盖摘要</h2><p>每条适用标准形成动态审核项</p></div></header><div className="summary-list">{Object.entries(remote.data.coverage.summary || {}).map(([key, value]) => <div key={key}><Status value={key} /><strong>{String(value)}</strong></div>)}</div></aside></div><section className="section"><header className="section-head"><div><h2>动态原子审核项</h2><p>确认适用后才会装配真实模型执行</p></div></header><div className="table-wrap"><table><thead><tr><th>条款</th><th>审核对象</th><th>执行方式</th><th>适用状态</th><th>操作</th></tr></thead><tbody>{remote.data.dynamic.map(item => <tr key={item.id}><td className="mono">{item.subject_code}</td><td><strong>{item.subject_name}</strong></td><td>{item.execution_mode === 'ai' ? 'AI 语义审核' : item.execution_mode}</td><td><Status value={item.applicability_status} /></td><td><div className="row-actions"><button title="确认适用" onClick={() => void decide(item.id, 'confirm')}><Check /></button><button title="确认不适用" onClick={() => void decide(item.id, 'exclude')}><CircleX /></button><button title="转人工判断" onClick={() => void decide(item.id, 'manual')}><FileSearch /></button></div></td></tr>)}</tbody></table></div></section>{modal && <Modal title="选择适用标准" close={() => setModal(false)}><div className="selection-list">{remote.data.catalog.flatMap(item => (item.versions || []).filter((v: any) => v.status === 'active').map((version: any) => <button key={version.id} onClick={() => void add(version.id)}><BookCheck /><span><strong>{item.standard_name}</strong><small className="mono">{version.full_code}</small></span><Plus /></button>))}</div></Modal>}</>
}

function Audit({ roundId }: { roundId: string }) {
  const { user } = useAuth(); const remote = useRemote(async () => { const [rules, executions, progress] = await Promise.all([api<any[]>(`/rounds/${roundId}/rules`), api<any[]>(`/rounds/${roundId}/rule-executions`), api<any>(`/rounds/${roundId}/audit/progress`)]); return { rules, executions, progress } }, [roundId]); const busy = useBusy()
  if (remote.loading) return <Spinner label="正在加载审核执行" />; if (remote.error || !remote.data) return <ErrorState error={remote.error} retry={remote.refresh} />
  const assemble = async () => { await busy.run(() => api(`/rounds/${roundId}/rules/assemble`, json('POST', {}))); await remote.refresh() }; const start = async () => { await busy.run(() => api(`/rounds/${roundId}/audit/start`, json('POST'))); await remote.refresh() }; const run = async (id: string) => { await busy.run(() => api(`/rule-executions/${id}/run`, json('POST'))); await remote.refresh() }
  return <><section className="progress-band"><div><span>审核进度</span><strong>{remote.data.progress?.progress_percent || 0}%</strong></div><div className="progress"><span style={{ width: `${remote.data.progress?.progress_percent || 0}%` }} /></div><Status value={remote.data.progress?.status} /><div className="actions"><button className="btn secondary" onClick={() => void assemble()}><BoxesIcon />装配规则</button><button className="btn primary" onClick={() => void start()}><Play />启动审核</button></div></section>{busy.error && <div className="form-error">{busy.error}</div>}<section className="section"><header className="section-head"><div><h2>规则执行</h2><p>确定性规则与动态 AI 审核共享统一尝试记录</p></div></header>{!remote.data.executions.length ? <Empty title="尚未生成执行记录" detail="先确认标准并装配规则，然后启动审核" /> : <div className="table-wrap"><table><thead><tr><th>规则</th><th>动态条款</th><th>状态</th><th>置信度</th><th>耗时</th><th>尝试</th><th></th></tr></thead><tbody>{remote.data.executions.map(item => <tr key={item.id}><td className="mono">{item.rule_code}</td><td>{item.input_snapshot?.dynamic_item?.subject_name || '-'}</td><td><Status value={item.status} /></td><td>{item.confidence ?? '-'}</td><td>{item.elapsed_ms ? `${item.elapsed_ms} ms` : '-'}</td><td>{item.attempt_count}</td><td>{user?.role === 'admin' && item.status === 'pending' && <button className="icon-link" title="立即执行" onClick={() => void run(item.id)}><Play /></button>}</td></tr>)}</tbody></table></div>}</section></>
}

function Issues({ roundId }: { roundId: string }) {
  const remote = useRemote(() => api<any[]>(`/issues?round_id=${roundId}`), [roundId]); const [selected, setSelected] = useState<any>(null); const [rerun, setRerun] = useState<string[] | null>(null); const busy = useBusy()
  useEffect(() => { if (remote.data?.length && !selected) setSelected(remote.data[0]) }, [remote.data, selected])
  if (remote.loading) return <Spinner label="正在加载问题复核" />; if (remote.error || !remote.data) return <ErrorState error={remote.error} retry={remote.refresh} />
  const decide = async (action: 'confirm' | 'reject' | 'close') => { await busy.run(() => api(`/issues/${selected.id}/${action}`, json('POST', { reason: action === 'confirm' ? '人工核对证据后确认' : '人工核对证据后处理' }))); setSelected(null); await remote.refresh() }
  const prepareRerun = async () => {
    const executionIds = [...new Set((selected.sources || []).map((source: any) => source.rule_execution_id).filter(Boolean))] as string[]
    const executions = await busy.run(() => Promise.all(executionIds.map(id => api<any>(`/rule-executions/${id}`))))
    setRerun([...new Set(executions.map(item => item.rule_code).filter(Boolean))])
  }
  const submitRerun = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const form = new FormData(event.currentTarget)
    await busy.run(() => api(`/rounds/${roundId}/audit/local-rerun`, json('POST', { affected_rule_codes: rerun, reason: String(form.get('reason')), input_change: { issue_id: selected.id } })))
    setRerun(null); await remote.refresh()
  }
  return <><section className="review-layout"><aside className="issue-queue"><header><strong>问题队列</strong><span>{remote.data.length}</span></header>{remote.data.map(item => <button key={item.id} className={selected?.id === item.id ? 'active' : ''} onClick={() => setSelected(item)}><Status value={item.status} /><strong>{item.title}</strong><small>{item.issue_code} · {item.severity}</small></button>)}</aside><div className="evidence-view">{!selected ? <Empty title="暂无问题" /> : <><header className="review-title"><div><h2>{selected.title}</h2><p>{selected.description}</p></div><Status value={selected.status} /></header><div className="evidence-columns"><Evidence title="客户证据" items={selected.evidence?.filter((x: any) => x.evidence_type === 'customer')} /><Evidence title="标准依据" items={selected.evidence?.filter((x: any) => x.evidence_type === 'standard')} /></div><section className="system-result"><ShieldCheck /><div><strong>系统结论</strong><p>{selected.system_conclusion || '无'}</p></div></section>{busy.error && <div className="form-error">{busy.error}</div>}<footer className="review-actions"><button className="btn danger" onClick={() => void decide('reject')}><CircleX />驳回</button><button className="btn secondary" onClick={() => void decide('close')}>关闭问题</button><button className="btn secondary" disabled={!selected.sources?.some((source: any) => source.rule_execution_id)} onClick={() => void prepareRerun()}><RotateCcw />局部重跑</button><button className="btn primary" onClick={() => void decide('confirm')}><Check />确认问题</button></footer></>}</div></section>{rerun && <Modal title="确认局部重跑" close={() => setRerun(null)}><form className="form-stack" onSubmit={submitRerun}><p className="notice"><ShieldCheck />只会重跑与当前问题关联的规则，不会覆盖其他审核结论。</p><label>受影响规则<input value={rerun.join('、')} readOnly /></label><label>重跑原因<textarea name="reason" required minLength={2} placeholder="说明补充或修订了哪些输入证据" /></label>{busy.error && <div className="form-error">{busy.error}</div>}<footer className="form-actions"><button type="button" className="btn secondary" onClick={() => setRerun(null)}>取消</button><button className="btn primary" disabled={!rerun.length || busy.busy}><RotateCcw />确认并入队</button></footer></form></Modal>}</>
}

function Reports({ roundId }: { roundId: string }) {
  const remote = useRemote(async () => (await api<any[]>('/reports')).filter(item => item.round_id === roundId), [roundId]); const busy = useBusy(); const [preview, setPreview] = useState<any>(null)
  if (remote.loading) return <Spinner label="正在加载报告" />; if (remote.error || !remote.data) return <ErrorState error={remote.error} retry={remote.refresh} />
  const create = async () => { await busy.run(() => api('/reports', json('POST', { round_id: roundId, report_type: 'formal', conclusion: 'through' }))); await remote.refresh() }; const publish = async (id: string) => { await busy.run(() => api(`/reports/${id}/publish`, json('POST', {}))); await remote.refresh() }
  const download = async (id: string, type: 'word' | 'pdf') => { const token = sessionStorage.getItem('coal_access_token'); const response = await fetch(`/api/v1/reports/${id}/artifacts/${type}/download`, { headers: { Authorization: `Bearer ${token}` } }); if (!response.ok) return; const url = URL.createObjectURL(await response.blob()); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `report.${type === 'word' ? 'docx' : 'pdf'}`; anchor.click(); URL.revokeObjectURL(url) }
  return <><section className="section"><header className="section-head"><div><h2>轮次报告</h2><p>发布前必须通过覆盖检查并完成问题人工确认</p></div><button className="btn primary" onClick={() => void create()}><Plus />生成报告</button></header>{!remote.data.length ? <Empty title="尚未生成报告" /> : <div className="table-wrap"><table><thead><tr><th>报告编号</th><th>结论</th><th>版本</th><th>状态</th><th>操作</th></tr></thead><tbody>{remote.data.map(item => <tr key={item.id}><td className="mono">{item.report_no}</td><td>{item.conclusion}</td><td>V{item.version_no}</td><td><Status value={item.status} /></td><td><div className="row-actions"><button title="预览" onClick={async () => setPreview(await api(`/reports/${item.id}/preview`))}><FileSearch /></button>{item.status !== 'published' ? <button title="发布" onClick={() => void publish(item.id)}><Check /></button> : <><button title="下载 Word" onClick={() => void download(item.id, 'word')}><Download /></button><button title="下载 PDF" onClick={() => void download(item.id, 'pdf')}><Download /></button></>}</div></td></tr>)}</tbody></table></div>}</section>{preview && <Modal title="报告内容预览" close={() => setPreview(null)}><pre className="report-preview">{JSON.stringify(preview.content, null, 2)}</pre></Modal>}</>
}

function Evidence({ title, items = [] }: { title: string; items?: any[] }) { return <section><h3>{title}</h3>{!items.length ? <Empty title="暂无证据" /> : items.map((item, index) => <article className="evidence" key={item.id || index}><header><span>{item.file_id ? `文件 ${item.file_id.slice(0, 8)}` : `条款 ${item.clause_id?.slice(0, 8)}`}</span>{item.page_no && <span>第 {item.page_no} 页</span>}</header><p>{item.excerpt_text}</p></article>)}</section> }
function Fact({ label, value, mono }: { label: string; value: any; mono?: boolean }) { return <div className="fact"><span>{label}</span><strong className={mono ? 'mono' : ''}>{String(value)}</strong></div> }
function BoxesIcon() { return <BookCheck /> }
